ForoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foro.urls')),
]

foro/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', home, name="home"),
    path('fLogin', fLogin, name="fLogin"),
    path('post/<id>', post, name="post"),
    path('register', register, name="register"),
    path('nuevo_post', nuevo_post, name="nuevo_post"),
    path('cerrar_sesion', cerrar_sesion, name="cerrar_sesion"),
    path('puntuacion/<id>/<type>', puntuacion, name="puntuacion"),
    path('borrar_post/<id>', borrar_post, name="borrar_post"),
    path('top_peliculas', top_peliculas, name="top_peliculas"),
    path('api/', include('rest_api.urls'))
]

rest_api/urls.py
from django.contrib import admin
from django.urls import path
from rest_api.views import *
from rest_api.viewsLogin import login

urlpatterns = [
    path('lista_posts/', lista_posts, name="lista_posts"),
    path('datos_post/<id>', vista_post_mod, name="vista_post_mod"),
    path('login/', login, name="login")
]

foro/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Hilo(models.Model):
    idHilo = models.AutoField(primary_key=True, verbose_name="Id del Hilo")
    tituloHilo = models.CharField(max_length=25, verbose_name="Titulo del Hilo")
    cuerpoHilo = models.CharField(max_length=255, verbose_name="Cuerpo del Hilo")
    puntosHilo = models.IntegerField(verbose_name="Puntuacion Hilo")
    autorHilo = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Comentario(models.Model):
    idComentario = models.AutoField(primary_key=True, verbose_name="Id del Comentario")
    cuerpoComentario = models.CharField(max_length=150, verbose_name="Cuerpo del Comentario")
    autorComentario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    padreComentario = models.ForeignKey(Hilo, on_delete=models.CASCADE)

foro/forms.py
from django import forms
from django.forms import ModelForm
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class UserForm(UserCreationForm):
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Ingrese la Contraseña'}))
    password2 = forms.CharField(label='Confirmar Contraseña',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirme la Contraseña'}))
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Primer Nombre'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Apellido'}),
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre de Usuario'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Correo Electronico'}),
        }

        labels={
            'first_name':'Primer Nombre',
            'last_name':'Apellido',
            'username':'Usuario',
            'email':'Correo',
        }

class PostForm(ModelForm):

    class Meta:
        model = Hilo
        fields = ['tituloHilo', 'cuerpoHilo', 'autorHilo', 'puntosHilo']

        widgets = {
            'tituloHilo':forms.TextInput(attrs={'class':'form-control','placeholder':'Dame un Titulo'}),
            'cuerpoHilo':forms.TextInput(attrs={'class':'form-control','placeholder':'El Cuerpo está Aqui'}),
        }

        labels={
            'tituloHilo':'Titulo',
            'cuerpoHilo':'Cuerpo',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comentario
        fields = ['cuerpoComentario', 'autorComentario', 'padreComentario']

        widgets = {
            'cuerpoComentario':forms.TextInput(attrs={'class':'form-control','placeholder':'Deja tu Opinion'}),
        }

foro/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from .models import Hilo
from django.db.models import Max
from .forms import *

# Create your views here.

def home(request):
    posts = Hilo.objects.all()
    postDia = Hilo.objects.latest('puntosHilo')

    datos = {
        'posts': posts,
        'postDia': postDia
    }
    return render(request, 'foro/home.html', datos)

def top_peliculas(request):
    return render(request, 'foro/top_peliculas.html')

@login_required(login_url='login')
def post(request, id):
    post = Hilo.objects.get(idHilo=id)
    comentarios = Comentario.objects.all().filter(padreComentario=id)
    puntos = PostForm(instance=post)
    datos = {
        'form' : CommentForm(),
        'post': post,
        'puntos': puntos,
        'comentarios': comentarios
    }

    if request.method == 'POST':
        formulario = CommentForm(request.POST)

        if formulario.is_valid():
            formulario.save()

    return render(request, 'foro/post.html', datos)

def fLogin(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(to="home")
    else:
        form = AuthenticationForm()
    return render(request, 'foro/login.html', {"form": form})

@login_required(login_url='login')
def nuevo_post(request):
    datos = {
        'form': PostForm()
    }
    if request.method == 'POST':
        formulario = PostForm(request.POST)
    
        if formulario.is_valid():
            formulario.save()
            formulario.puntosHilo = 0
            datos['mensaje'] = "Guardado correctamente"

    
    return render(request, 'foro/nuevo_post.html', datos)

def register(request):
    datos = {
        'form': UserForm()
    }
    
    if request.method == 'POST':
        formulario = UserForm(request.POST)

        if formulario.is_valid():
            formulario.save()
            datos['mensaje'] = "Guardado correctamente"
            
            
    return render(request, 'foro/register.html', datos)

@login_required(login_url='login')
def puntuacion(request, id, type):
    post = Hilo.objects.get(idHilo=id)
    puntos = post.puntosHilo
    
    if type == 'menos':
        post.puntosHilo = puntos - 1
    else:
        post.puntosHilo = puntos + 1

    post.save()

    return redirect("/post/" + id)

@login_required(login_url='login')
def borrar_post(request, id):
    post = Hilo.objects.get(idHilo=id)
    post.delete()

    return redirect(to="home")

def cerrar_sesion(request):
    logout(request)
    return redirect(to="home")

rest_api/views.py
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from foro.models import Hilo
from .serializers import PostSerializer

from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

@csrf_exempt
@api_view(['GET','POST'])
@permission_classes((IsAuthenticated,))
def lista_posts(request):
    if request.method == 'GET':
        post = Hilo.objects.all()
        serializer = PostSerializer(post, many=True)
        return Response(serializer.data)
    
    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = PostSerializer(data = data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status= status.HTTP_201_CREATED)
        else:
            return Response(serializer.error, status= status.HTTP_400_BAD_REQUEST)
        
@api_view(['GET','PUT','DELETE'])
@permission_classes((IsAuthenticated,))
def vista_post_mod(request, id):
    try:
        p = Hilo.objects.get(idHilo=id)
    except Hilo.DoesNotExist:
        return Response(status= status.HTTP_404_NOT_FOUND)
    
    if request.method == 'GET':
        serializer = PostSerializer(p)
        return Response(serializer.data)
    
    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = PostSerializer(p, data = data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status= status.HTTP_400_BAD_REQUEST)
        
    elif request.method == 'DELETE':
        p.delete()
        return Response(status= status.HTTP_204_NO_CONTENT)

foro/templates/foro/home.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'foro/css/bootstrap/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'foro/css/style.css' %}"/>
        <title>foro</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <script src="{% static 'foro/js/jquery-3.7.1.min.js' %}"></script>
    </head>
    <body>
        <div class="grid-container">

            <div class="d-header">
                <div>
                    Fororo mororo - {{user.username}}
                </div>
            </div>

            <div class="d-menu">
                <ul>
                    {% if user.is_authenticated %}
                    <a href="{% url 'cerrar_sesion' %}"><li>Cerrar Sesion</li></a>
                    <a href="{% url 'nuevo_post' %}"><li>Crear Hilo</li></a>
                    {% else %}
                    <a href="{% url 'register' %}"><li>Crear Cuenta</li></a>
                    <a href="{% url 'login' %}"><li>Iniciar Sesion</li></a>
                    {% endif %}
                </ul>
            </div>

            <div class="d-main">

                {% for post in posts %}
                <a href="{% url 'post' post.idHilo %}">
                <section class="post--00">
                    <h1>{{ post.tituloHilo }}</h1>
                    <p>{{ post.cuerpoHilo }}</p>
                </section>
                </a>
                {% endfor %}

            </div>

            <a href="{% url 'post' postDia.idHilo %}">
            <div class="d-right">
                <div>
                    Hilo del Dia
                </div>
                <div class="d-img">
                    <h2>{{postDia.tituloHilo}}</h1>
                    <p>{{postDia.cuerpoHilo}}</p>
                </div>
                
            </div>
            </a>

            <div class="d-footer">
                <div>
                    
                </div>
            </div>

        </div>

    </body>
    <footer>
        
    </footer>
</html>

foro/templates/foro/login.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'foro/css/bootstrap/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'foro/css/style.css'%}"/>

        <script src="{% static 'foro/js/jquery-3.7.1.min.js' %}"></script>
    </head>

    <body>
        <div class="grid-container">

            <div class="d-header">
                <div>
                    Fororo mororo - Iniciar Sesion
                </div>
            </div>

            <div class="d-menu">
                <ul>
                    <a href="{% url 'home' %}"><li>Volver al Home</li></a>
                    <a href="{% url 'register' %}"><li>Crear Cuenta</li></a>
                </ul>
            </div>

            <div class="d-main">
                <form class="form-with-validation" method="post" action="" id="formulario">
                    {% csrf_token %}
                    <div class="col-lg-6">
                        <label class="form-label">Nombre de Usuario:</label>
                        {{form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="form-label">Contraseña: </label>
                        {{form.password}}
                    </div>
                
                    <input type="submit" class="btn btn-primary" id="enviar" value="Iniciar Sesion">

                    <script type="text/javascript">
                    $(document).ready(function () {
                        $(".alert").hide();
                    });
                    </script>
                    <div id="error" class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    
                    

                </form>
                <div id="alert-box" class="alert alert-success" role="alert">
                    {{mensaje}}
                </div>
            </div>
            

            <div class="d-footer">
                <div>
                    
                </div>
            </div>

        </div>
            
    </body>

    <footer>



    </footer>
</html>

foro/templates/foro/nuevo_post.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'foro/css/bootstrap/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'foro/css/style.css' %}"/>
        <title>foro</title>
        <meta charset="UTF-8">
        <script src="{% static 'foro/js/jquery-3.7.1.min.js' %}"></script>
    </head>
    <body>
        <div class="grid-container">

            <div class="d-header">
                <div>
                    Fororo mororo - {{user.username}}
                </div>
            </div>

            <div class="d-menu">
                <ul>
                    <a href="{% url 'home' %}"><li>Volver al Home</li></a>
                    <a href="{% url 'cerrar_sesion' %}"><li>Cerrar Sesion</li></a>
                </ul>
            </div>

            <div class="d-main">
                <div class="d-main">
                <form method="post" action="" id="formulario">
                    {% csrf_token %}
                    <div class="col-lg-6">
                        <label class="form-label">{{form.tituloHilo.label_tag}}</label>
                        {{form.tituloHilo}}
                    </div>
                    <div class="row-cols-1">
                        <label class="form-label">{{form.cuerpoHilo.label_tag}}</label>
                        {{form.cuerpoHilo}}
                    </div>
                    <input type="text" value="{{user.pk}}" name="autorHilo" hidden>
                    <input type="text" value="0" name="puntosHilo" hidden>
                
                    <input type="submit" class="btn btn-primary" id="enviar" value="Crear Hilo">
                    <input type="reset" class="btn btn-danger" id="limpiar" value="Limpiar">

                    <div id="error" class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>

                </form>
                <div id="alert-box" class="alert alert-success" role="alert">
                    {{ mensaje }}
                </div>
            </div>
                

            </div>

            <div class="d-footer">
                <div>
                    
                </div>
            </div>

        </div>

    </body>
    <footer>
        
    </footer>
</html>

foro/templates/foro/post.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'foro/css/bootstrap/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'foro/css/style.css' %}"/>
        <title>foro</title>
        <meta charset="UTF-8">
        <script src="{% static 'foro/js/jquery-3.7.1.min.js' %}"></script>
    </head>
    <body>
        <div class="grid-container">

            <div class="d-header">
                <div>
                    Fororo mororo - {{user.username}}
                </div>
            </div>

            <div class="d-menu">
                <ul>
                    <a href="{% url 'home' %}"><li>Volver al Home</li></a>
                    <a href="{% url 'cerrar_sesion' %}"><li>Cerrar Sesion</li></a>

                    {% if perms.foro.delete_hilo or user.pk == post.autorHilo.pk %}
                    <a href="{% url 'borrar_post' post.idHilo %}"><li>Borrar Post</li></a>
                    {% endif %}
                </ul>
            </div>

            <div class="d-main">
                <section>
                    <h1>{{post.tituloHilo}}</h1>
                    <p>{{post.cuerpoHilo}}</p>
                </section>
                <div class="puntacion">
                    <a href="{% url 'puntuacion' post.idHilo 'mas' %}">
                    <img src="{%static 'foro/img/like.png'%}" height="40px" style="float: left;">
                    </a>
                    <p style="float: left;">{{post.puntosHilo}}</p>
                    <a href="{% url 'puntuacion' post.idHilo 'menos' %}">
                    <img src="{%static 'foro/img/dislike.png'%}" height="40px" style="float: left;">
                    </a>
                </div>
                <p style="float: right;">Autor: {{post.autorHilo}}</p><br><br><br>
                <h2>Comentarios</h2>
                {% for comm in comentarios %}

                <section>{{comm.cuerpoComentario}}</section>

                {% endfor %}
                <form method="post" action="" id="formulario">
                    {% csrf_token %}
                    <div class="col-lg-6">
                        <label class="form-label">Agregar un Comentario:</label>
                        {{form.cuerpoComentario}}
                    </div>
                    <input type="text" value="{{user.pk}}" name="autorComentario" hidden>
                    <input type="text" value="{{post.idHilo}}" name="padreComentario" hidden>

                    <input type="submit" class="btn btn-primary" id="enviar" value="Añadir Comentario" style="margin-top: 15px;">
                </form>
            </div>

            <div class="d-footer">
                
            </div>

        </div>

    </body>
    <footer>
        
    </footer>
</html>

foro/templates/foro/register.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'foro/css/bootstrap/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'foro/css/style.css'%}"/>

        <script src="{% static 'foro/js/jquery-3.7.1.min.js' %}"></script>
    </head>

    <body>
        <div class="grid-container">

            <div class="d-header">
                <div>
                    Fororo mororo - Registrar Cuenta
                </div>
            </div>

            <div class="d-menu">
                <ul>
                    <a href="{% url 'home' %}"><li>Volver al Home</li></a>
                    <a href="{% url 'fLogin' %}"><li>Iniciar Sesion</li></a>
                </ul>
            </div>

            <div class="d-main">
                <form method="post" action="" id="formulario">
                    {% csrf_token %}
                    <div class="col-lg-6">
                        <label class="form-label">{{form.first_name.label_tag}}</label>
                        {{form.first_name}}
                    </div>
                    <div class="col-lg-6">
                        <label class="form-label">{{form.last_name.label_tag}}</label>
                        {{form.last_name}}
                    </div>
                    <div class="col-lg-6">
                        <label class="form-label">{{form.username.label_tag}}</label>
                        {{form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="form-label">{{form.password1.label_tag}}</label>
                        {{form.password1}}
                    </div>
                    <div class="col-lg-6">
                        <label class="form-label">{{form.password2.label_tag}}</label>
                        {{form.password2}}
                    </div>
                
                    <input type="submit" class="btn btn-primary" id="enviar" value="Crear Cuenta">
                    <input type="reset" class="btn btn-danger" id="limpiar" value="Limpiar">

                    <div id="error" class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>

                </form>
                <div id="alert-box" class="alert alert-success" role="alert">
                    {{mensaje}}
                </div>
            </div>
            

            <div class="d-footer">
                <div>
                    
                </div>
            </div>

        </div>
            
    </body>

    <footer>



    </footer>
</html>

foro/templates/foro/top_peliculas.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'foro/css/bootstrap/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'foro/css/style.css' %}"/>
        <title>foro</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <script src="{% static 'foro/js/jquery-3.7.1.min.js' %}"></script>
        <script src="{% static 'foro/js/tmdb.js' %}"></script>
    </head>
    <body>
        <div class="grid-container">

            <div class="d-header">
                <div>
                    Fororo mororo - {{user.username}}
                </div>
            </div>

            <div class="d-menu">
                <ul>
                    <a href="{% url 'home' %}"><li>Volver al Home</li></a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'cerrar_sesion' %}"><li>Cerrar Sesion</li></a>
                    <a href="{% url 'nuevo_post' %}"><li>Crear Hilo</li></a>
                    {% else %}
                    <a href="{% url 'register' %}"><li>Crear Cuenta</li></a>
                    <a href="{% url 'fLogin' %}"><li>Iniciar Sesion</li></a>
                    {% endif %}
                </ul>
            </div>

            <div class="d-main">
                <div class="row" id="pelis">
                </div>
            </div>

            <div class="d-footer">
                
            </div>

        </div>

    </body>
    <footer>
        
    </footer>
</html>